### ISSUE TITLE
Clarify that we only work with iframes

### ISSUE THREAD

**Issue by deviantintegral** [Lullabot/ckeditor_embed_code#2]
The readme says "like an iframe" - is the plan to somehow sanitize other tags too? https://github.com/Lullabot/ckeditor_embed_code/blob/master/src/Plugin/Filter/EmbedCodeFilter.php#L61 is hardcoded to an iframe today.

**Comment by juanolalla** [comment]
The reason to call it Embed Code is to leave this opened to include other possible tags too, like a whitelisted script tags or things like that. For the moments, it only works with iframes.

**Comment by deviantintegral** [comment]
Sounds good to me. How about documenting that in the readme, unless you expect to add a whitelist soon?

**Comment by juanolalla** [comment]
:+1:
